spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/flavorscape
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create


  redis:
    host: redis #localhost redis
    port: 6379


  session:
    timeout: 60m
    store-type: redis


  kafka:
    bootstrap-servers: kafka:9092 #localhost:9092 kafka:9092
    topic:
      organizations: organizationTopic


api_key:
  2gis: #https://platform.2gis.ru/ru/keys получить api ключ 2gis
  ai: #https://openrouter.ai/ получить api ключ ai (нужен именно gpt)
